# Generated by Django 2.0.6 on 2018-06-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_code', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField(verbose_name='call started')),
                ('ended_at', models.DateTimeField(verbose_name='call ended')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=2)),
                ('phone_number', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='fk_destination_phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='billing.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='call',
            name='fk_origin_phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='billing.PhoneNumber'),
        ),
    ]
