# Generated by Django 2.0.6 on 2018-06-19 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('area_code', 'phone_number')},
        ),
    ]
