# Generated by Django 2.0.6 on 2018-06-27 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180626_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('seconds', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_billing_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.BillingRule')),
                ('fk_call', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.Call')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('fk_call', 'fk_billing_rule')},
        ),
    ]
