# Generated by Django 2.0.6 on 2018-07-10 18:04

from django.db import migrations, models
from datetime import time


def forwards(apps, schema_editor):
    BillingRule = apps.get_model('billing', 'BillingRule')
    BillingRule.objects.create(
        id=1,
        time_start=time(6, 0, 1),
        time_end=time(22, 0, 0),
        fixed_charge=0.36,
        by_minute_charge=0.09,
        is_active=True,
    )
    BillingRule.objects.create(
        id=2,
        time_start=time(22, 0, 1),
        time_end=time(6, 0, 0),
        fixed_charge=0.36,
        by_minute_charge=0.0,
        is_active=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0007_auto_20180710_1804'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
