# Generated by Django 2.0.6 on 2018-07-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_setup_billing_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='area_code',
        ),
    ]
