# Generated by Django 2.0.6 on 2018-07-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20180712_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=11, unique=True),
        ),
    ]
