# Generated by Django 2.0.6 on 2018-07-10 18:04

from django.db import migrations, models
from ..models import BillingRule


def forwards(apps, schema_editor):
    Configuration = apps.get_model('billing', 'Configuration')
    Configuration.objects.create(
        name=BillingRule.FIXED_CHARGE_CONFIG,
        value='0.36',
    )


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0011_configuration'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
