# Generated by Django 2.0.6 on 2018-07-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20180716_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='fk_origin_phone_number',
        ),
        migrations.AddField(
            model_name='call',
            name='fk_source_phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source', to='billing.PhoneNumber'),
        ),
    ]
